spring:
  application:
    name: cinemabooking

  # H2
  datasource:
    url: jdbc:h2:mem:kino_db
    driverClassName: org.h2.Driver
    username: sa
    password:

  # H2 - pozwala podgl?da? baz? w przegl?darce
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA i Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # automatycznie tworzy tabele
    show-sql: true # Pokazuje zapytania SQL w konsoli

  # Thymeleaf (?eby nie cache'owa? widoków)
  thymeleaf:
    cache: false