spring:
  application:
    name: cinemabooking

  # H2
  datasource:
    url: jdbc:h2:mem:kino_db
    driverClassName: org.h2.Driver
    username: sa
    password:

  # H2 - pozwala podgladac baze w przegladarce
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA i Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # automatycznie tworzy tabele
    show-sql: true # Pokazuje zapytania SQL w konsoli

  # Thymeleaf (zeby nie cacheowal widoków)
  thymeleaf:
    cache: false